name: Run Python Program

on:
   push:
       branches:
       -  main

jobs:
    streamlit-job:

       steps:
       - name: checkout code
         uses: actions/checkout@v2

       - name: setup python
         run: echo'welcome to github action'
